
name: Build and test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    uses: GTNewHorizons/GoodGenerator/.github/workflows/test.yml@test2
    secrets: inherit
    with:
      timeout: 240
